---
title: "Viz and EDA I"
author: "Wenyan Ma"
date: "2022-09-29"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


making a scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

make a different scatterplot
```{r}
weather_df %>%
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```


let keep making the same plot but different

```{r}
weather_scatterplot =
  weather_df %>%
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_scatterplot +
  geom_point()
```


make it fancy
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + #if add color here, will have independent smooth line for all the three groups, so 3 lines
  geom_point(aes(color = name)) +
  geom_smooth()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(alpha = 0.3, aes(color = name)) + #alpha for transparency
  geom_smooth(se = FALSE)
```


maybe make separate panels

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```


'tmax' vs 'tmin' is boring, spice it up 

seasonal trend
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.3, aes(size = prcp)) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```


## some quick stuff 

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```


## Univariate plots

histograms, barplots, boxplots, violines ...

```{r}
weather_df %>% 
  ggplot(aes(x = tmax)) + 
  geom_histogram()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```

another option

```{r}
weather_df %>% 
   ggplot(aes(x = tmax, color = name)) +
  geom_density()
```

boxplot

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

violin plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.3)
```

ridge plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

## Saving and embedding plots

save a plot
```{r}
weather_scatterplot = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.3, aes(size = prcp)) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_scatterplot

ggsave("results/weather_scatterplot.pdf", weather_scatterplot,
       width = 8, height = 5)
```








